version: "3"
services:
  node:
    build:
      context: ./node
      dockerfile: Dockerfile
    container_name: node
    env_file:
      - .env
    ports:
      - 3000:3000
    expose:
      - 3000
    volumes:
      - "./node:/usr/src/node"
      - "/usr/src/node/node_modules"
  mysql:
    # platform: linux/amd64 # m1
    image: "mysql:8.0.28"
    logging:
      driver: none
    restart: always
    container_name: mysql
    ports:
      - "3306:3306"
    env_file:
      - .env
    volumes:
      - ./mysql/conf.d:/etc/mysql/conf.d
      - ./mysql/data:/var/lib//mysql 
      - ./mysql/initdb.d:/docker-entrypoint-initdb.d
    # cap_add:
    #   - SYS_NICE
    environment:
      MYSQL_DATABASE: DATABASE_NAME
      MYSQL_ROOT_PASSWORD: password
  